global:
  scrape_interval: 15s
  # evaluation_interval: 15s # Evaluación de reglas cada x tiempo

# Alertmanager configuration
# alerting:
#   alertmanagers:
#     - static_configs:
#     - targets:
#       - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
# rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: ["127.0.0.1:9090"]

  - job_name: "adopciones"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["host.docker.internal:8083"]

  - job_name: "adoptantes"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["host.docker.internal:8081"]

  - job_name: "animales"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["host.docker.internal:8082"]

  - job_name: "voluntarios"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ "host.docker.internal:8080" ]