server:
  port: 8083

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  config:
    activate:
      on-profile: default
  application:
    name: adopciones
    zipkin: http://zipkin:9411
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: admin123
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher