spring:
  application:
    name: voluntarios
  cloud:
    config:
      uri: http://localhost:8888
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  file:
    name: ./logs/voluntarios.log